apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: development
    component: rabbitmq
    tier: Database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: development
      component: rabbitmq
      tier: Database
  template:
    metadata:
      labels:
        project: roboshop
        environment: development
        component: rabbitmq
        tier: Database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: development
    component: rabbitmq
    tier: Database
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672