apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: development
    component: mongodb
    tier: Database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: development
      component: mongodb
      tier: Database
  template:
    metadata:
      labels:
        project: roboshop
        environment: development
        component: mongodb
        tier: Database
    spec:
      containers:
      - name: mongodb
        image: manikantaakula/mongodb:v1
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: development
    component: mongodb
    tier: Database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
