apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: development
    component: mysql
    tier: Database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: development
      component: mysql
      tier: Database
  template:
    metadata:
      labels:
        project: roboshop
        environment: development
        component: mysql
        tier: Database
    spec:
      containers:
      - name: mysql
        image: manikantaakula/mysql:v1
        imagePullPolicy: Always
        # ports:
        # - containerPort: 80
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 15
        #   periodSeconds: 15
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: development
    component: mysql
    tier: Database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306